name: flutter_quizz_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.2
  crypto: ^3.0.3
  firebase_app_check: ^0.2.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  json_annotation: ^4.8.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/covers/
    - assets/congrats.gif